version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/livestorm
    docker:
      # this is important to use proper image with browsers support
      - image: circleci/ruby:2.5.1-node-browsers

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        # remove space between { {
        key: livestorm-{ { checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-save
        # remove space between { {
        key: livestorm-{ { checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run cucumber
      - type: shell
        command: |
          mkdir -p ~/report
          bundle exec cucumber --format junit --out ~/report/junit.xml
        when: always

      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: ~/report